### ISSUE TITLE
Why does not Base64 encode SAMLResponse?

### ISSUE THREAD

**Issue by thwblueboy** [capriza/samling#1]
Hi, why does not this tool Base64 encode SAMLResponse?

**Comment by fujifish** [comment]
Good catch. Fixed in version 0.1.1

**Comment by thwblueboy** [comment]
Thanks Nadav, that would be better if you will update the live page: https://capriza.github.io/samling/samling.html 👍

**Comment by fujifish** [comment]
It is already updated, perhaps you have a cached version? try to run in an incognito window.
