### ISSUE TITLE
SimpleSAML_Error_Error: UNHANDLEDEXCEPTION

### ISSUE THREAD

**Issue by congas1983** [capriza/samling#11]
SimpleSAML_Error_Error: UNHANDLEDEXCEPTION

Backtrace:
1 www/_include.php:45 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: SimpleSAML_Error_Exception: Cannot retrieve metadata for IdP 'https://capriza.github.io/samling/samling.html' because it isn't a valid IdP for this SP.
Backtrace:
2 modules/saml/lib/Auth/Source/SP.php:112 (sspmod_saml_Auth_Source_SP::getIdPMetadata)
1 modules/saml/www/sp/saml2-acs.php:100 (require)
0 www/module.php:135 (N/A)

this happens when I log off from my local application and try to log in again by sso.

**Comment by fujifish** [comment]
Where are you trying to obtain the metadata from?
The readme pointed to the wrong URL, it's now fixed.
The correct URL is https://capriza.github.io/samling/public/metadata.xml.
Does it solve your issue?

**Comment by congas1983** [comment]
in authsources.php
'idp'=>'https://capriza.github.io/samling/public/metadata.xml'

and the file saml20-idp-remote
'entityID' =>  'http://capriza.com/samling',   or  entityID =>'https://capriza.github.io/samling/public/metadata.xml'

Please help

**Comment by congas1983** [comment]
Backtrace:
1 www/_include.php:45 (SimpleSAML_exception_handler)
0 [builtin] (N/A)
Caused by: SimpleSAML_Error_Exception: Could not find the metadata of an IdP with entity ID 'https://capriza.github.io/samling/public/metadata.xml'
Backtrace:
6 modules/saml/lib/Auth/Source/SP.php:135 (sspmod_saml_Auth_Source_SP::getIdPMetadata)
5 modules/saml/lib/Auth/Source/SP.php:328 (sspmod_saml_Auth_Source_SP::startSSO)
4 modules/saml/lib/Auth/Source/SP.php:431 (sspmod_saml_Auth_Source_SP::authenticate)
3 lib/SimpleSAML/Auth/Source.php:193 (SimpleSAML_Auth_Source::initLogin)
2 lib/SimpleSAML/Auth/Simple.php:161 (SimpleSAML\Auth\Simple::login)
1 modules/core/www/authenticate.php:36 (require)
0 www/module.php:135 (N/A)

**Comment by fujifish** [comment]
I'm not familiar with PHP, so I can't really help.
I can only suggest the following:
1. in authsources.php: 
```php
'idp'=>'http://capriza.com/samling'
```
2. in saml20-idp-remote:
```php
$metadata['http://capriza.com/samling'] = array (
  'entityid' => 'http://capriza.com/samling'
  ...THE REST OF SETTINGS FROM https://capriza.github.io/samling/public/metadata.xml...
);
```

**Comment by congas1983** [comment]
so I have it configured and it generates the first reported error

**Comment by fujifish** [comment]
Can you share the stacktrace and the full authsources.php and saml20-idp-remote sources?

**Comment by fujifish** [comment]
Also, how are you calling the `getIdPMetadata` method?

**Comment by congas1983** [comment]
authsources.php

'default-sp' => array(
        'saml:SP',

        // The entity ID of this SP.
        // Can be NULL/unset, in which case an entity ID is generated based on the metadata URL.
        'entityID' =>  null,

        // The entity ID of the IdP this should SP should contact.
        // Can be NULL/unset, in which case the user will be shown a list of available IdPs.
        'idp' =>'http://capriza.com/samling',
  

        // The URL to the discovery service.
        // Can be NULL/unset, in which case a builtin discovery service will be used.
        'discoURL' => null,
),

**Comment by congas1983** [comment]
id-remote
$metadata['http://capriza.com/samling'] = array (
  'entityID' =>  'http://capriza.com/samling',
  'contacts' =>
  array (
  ),
  'metadata-set' => 'saml20-idp-remote',

  'SingleSignOnService' =>
  array (
    0 =>
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
      'Location' => 'https://capriza.github.io/samling/samling.html',
    ),
  ),

  'SingleLogoutService' =>
  array (
    0 =>
    array (
      'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
      'Location' => 'https://capriza.github.io/samling/samling.html',
    ),
  ),
  'ArtifactResolutionService' =>
  array (
  ),
  'NameIDFormats' =>
  array (
    0 => 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
  ),
  'keys' =>
  array (
    0 =>
    array (
      'encryption' => false,    
      'signing' => true,
      'type' => 'X509Certificate',
      'X509Certificate' => 'MIICpzCCAhACCQDuFX0Db5iljDANBgkqhkiG9w0BAQsFADCBlzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExEjAQBgNVBAcMCVBhbG8gQWx0bzEQMA4GA1UECgwHU2FtbGluZzEPMA0GA1UECwwGU2FsaW5nMRQwEgYDVQQDDAtjYXByaXphLmNvbTEmMCQGCSqGSIb3DQEJARYXZW5naW5lZXJpbmdAY2Fwcml6YS5jb20wHhcNMTgwNTE1MTgxMTEwWhcNMjgwNTEyMTgxMTEwWjCBlzELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExEjAQBgNVBAcMCVBhbG8gQWx0bzEQMA4GA1UECgwHU2FtbGluZzEPMA0GA1UECwwGU2FsaW5nMRQwEgYDVQQDDAtjYXByaXphLmNvbTEmMCQGCSqGSIb3DQEJARYXZW5naW5lZXJpbmdAY2Fwcml6YS5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAJEBNDJKH5nXr0hZKcSNIY1l4HeYLPBEKJLXyAnoFTdgGrvi40YyIx9lHh0LbDVWCgxJp21BmKll0CkgmeKidvGlr3FUwtETro44L+SgmjiJNbftvFxhNkgA26O2GDQuBoQwgSiagVadWXwJKkodH8tx4ojBPYK1pBO8fHf3wOnxAgMBAAEwDQYJKoZIhvcNAQELBQADgYEACIylhvh6T758hcZjAQJiV7rMRg+Omb68iJI4L9f0cyBcJENR+1LQNgUGyFDMm9Wm9o81CuIKBnfpEE2Jfcs76YVWRJy5xJ11GFKJJ5T0NEB7txbUQPoJOeNoE736lF5vYw6YKp8fJqPW0L2PLWe9qTn8hxpdnjo3k6r5gXyl8tk=',
    ),
  ),
);

**Comment by ndarwincorn** [comment]
So I just happened to be writing a test for our simplesamlphp implementation using samling today, and inevitably hit this as well.

@congas1983 - try the following config:
`config/authsources.php`
```
    'default-sp' => array(
        'saml:SP',
	'privatekey' => 'server.pem',
	'certificate' => 'server.crt',

        // The entity ID of this SP.
        // Can be NULL/unset, in which case an entity ID is generated based on the metadata URL.
        'entityID' => null,

        // The entity ID of the IdP this should SP should contact.
        // Can be NULL/unset, in which case the user will be shown a list of available IdPs.
        'idp' => null,
```
`metadata/saml20-idp-remote.php`
```
/*
 * Capriza Samling test IdP
 */

$metadata['https://capriza.github.io/samling/samling.html'] = array (
  'entityid' => 'https://capriza.github.io/samling/samling.html',
...
```

When you run the test, pick the correct IdP if you have more than one. Or you could probably use `'https://capriza.github.io/samling/samling.html'` as your entityId in the SP config (`config/authsources.php`).

**Comment by congas1983** [comment]
Tanks 
it worked correctly

**Comment by ndarwincorn** [comment]
@fujifish 

It seems like when Samling recieves a request from the SP it auto-populates `Issuer` with `https://capriza.github.io/samling/samling.html`, which is what the SimpleSamlPHP SP expects to match against the EntityID. My knowledge of SAML is pretty superficial so I dunno whether it's Samling or SimpleSamlPHP not following the spec here (i.e. whether Issuer needs to match EntityID in the metadata).

**Comment by fujifish** [comment]
@ndarwincorn you are correct, the metadata specifies `http://capriza.com/samling` as the entityId, however that value is never used since samling uses the destination of the request `https://capriza.github.io/samling/samling.html` as the actual entityid and issuer during a real SAML transaction.
I've fixed the metadata and defaults to return `https://capriza.github.io/samling/samling.html` as the entity id to align with the transaction details.
