### ISSUE TITLE
IdP metadata certificate / certificate for signing response

### ISSUE THREAD

**Issue by manuelwaltschek** [capriza/samling#12]
Hello there,

today I tried to mock an IdP integration with samling and faced an issue where the certificate in the response which is used for signing the assertion is not the same as the one published in the IdP metadata. Is this intended behaviour? Does this happen on purpose or is it a bug?

See for details:
https://github.com/onelogin/java-saml/issues/181#issuecomment-417395447

**Comment by manuelwaltschek** [comment]
Hello @fujifish, yes I did and also saved it in the local storage of my browser. The validation of the response signature is successful when using the generated public key, but the framework (onelogin saml-java) I am using for the SP implementation is using the certificate of the IdPs metadata for validation which is resulting in an error. Is it intended for samling to use a different certificate for the singing of response assertions than the one which is published in the metadata?

Refer to https://www.sslshopper.com/certificate-decoder.html and https://www.samltool.com/validate_response.php if you want to try it yourself.

**Comment by fujifish** [comment]
Currently the metadata is a static file containing the default public certificate of samling.
The problem you're having is due to the generation of a new key pair.
I'll start to work on a solution to dynamically create the metadata with the correct public cert.

**Comment by manuelwaltschek** [comment]
@fujifish thank you for your reply, I was just unsure if this was common behaviour and if I need to consider this case when implementing the SP. 

I'll leave this issue open for now.

**Comment by fujifish** [comment]
Keep in mind that I have no way of hosting a dynamic metadata as a _downloadable_ file since samling is a complete static site.
The only option that can be made available is to _display_ a dynamic metadata in the bowser so you'll only be able to copy/paste it, not import directly from samling.

**Comment by fujifish** [comment]
Samling now displays the correct certificate in the metadata when viewed from the browser.
Downloading the metadata.xml still provides the default certificate (since it's a static file)
