### ISSUE TITLE
assertionConsumerService binding HTTP-POST

### ISSUE THREAD

**Issue by pedro380085** [capriza/samling#13]
Hi, I'm using the https://github.com/onelogin/php-saml library in a project, but they only accept 'binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST' at their assertionConsumerService uri. Samling has support for this method or it is HTTP-Redirect only?

**Comment by fujifish** [comment]
Samling always sends the assertion back via POST to the assertion consumer
