### ISSUE TITLE
Expired Session

### ISSUE THREAD

**Issue by adussaq** [capriza/samling#15]
I have tried this tool on two different browsers and had the same issue. The redirects and everything else work, however when it actually gets the information to my server, the decrypted message says that the session has expired, which makes no sense since I set everything to last for days.

Any help you can offer would be greatly appreciated. Thank you.

The exact error is:
```
"ERR_EXPIRED_SESSION"
```

**Comment by fujifish** [comment]
Would be helpful if you posted the SAML response so I can take a look at the expiration statement

**Comment by adussaq** [comment]
I apologize, your tool is working just fine. I was using a library and did not realize that error was being generated by the library itself.
