### ISSUE TITLE
Support Signed Response

### ISSUE THREAD

**Issue by hiro2k** [capriza/samling#18]
Hi I'm trying to use samling as the iDP with a Spring/OpenSAML service provider but it barfs because it requires the entire Response message to be signed, not just the Assertations. I looked in the documentation and the source code and couldn't find any way to toggle this behavior.

Could you see about adding support for this as well?
Thanks

**Comment by fujifish** [comment]
Added a "Sign Response" checkbox to the options page, make sure to check it before clicking on the "Next" button
