### ISSUE TITLE
attributes in the wrong spot

### ISSUE THREAD

**Issue by p-is-for-pangolin** [capriza/samling#3]
When including SAML attributes, the XML generated looks like this:

```
<samlp:Response>
  <saml:Assertion>...</saml:Assertion>
  <saml:AttributeStatement>...</saml:AttributeStatement>
</samlp:Response>
```

When, according to the SAML Core spec it should look like this:

```
<samlp:Response>
  <saml:Assertion>
    <saml:AttributeStatement>...</saml:AttributeStatement>
  </saml:Assertion>
</samlp:Response>
```

It looks like in the file "saml.js" where it currently says:
`doc.appendChild(statement);`
it should instead say something like:
`doc.documentElement.appendChild(statement);`

**Comment by fujifish** [comment]
Fixed. Thank you!
