### ISSUE TITLE
x2 Base64 Encoding in Post Data

### ISSUE THREAD

**Issue by BradPenwarden** [capriza/samling#4]
I have noticed when inspecting the response Parameters and running through online utilities - like https://www.samltool.com/base64.php, I need to run the base64 decode twice to get the desired response XML for decryption.

Was this by design? Is this a standard to expect others to use.

**Comment by fujifish** [comment]
I'm not seeing it encoded twice, neither in code nor via testing. 
In fact, if it were encoded twice no SP would be able to decode the SAML response.
Can you paste a 2x encoded example?

**Comment by BradPenwarden** [comment]
After some tests I was able to get this to occur when receiving an error from my Service Provider, and hitting the back button to return to SAMLING.

On returning to the "SAML Response" tab , the encoded response, was encoded again. 

Closing issue.
