### ISSUE TITLE
SubjectConfirmationData missing attributes in generated Response

### ISSUE THREAD

**Issue by amergey** [capriza/samling#5]
Hello,
It seems generated token is missing some pieces related to SubjectConfirmationData, according to SAML 2.0 specs in oasis:

**The bearer <SubjectConfirmation> element described above MUST contain a <SubjectConfirmationData> element that contains a Recipient attribute containing the service provider's assertion consumer service URL and a NotOnOrAfter attribute that limits the window during which the assertion can be delivered. It MAY contain an Address attribute limiting the client address from which the assertion can be delivered. It MUST NOT contain a NotBefore attribute. If the containing message is in response to an <AuthnRequest>, then the InResponseTo attribute MUST match the request's ID.** 

Currently reponse token contains 
```
<saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
	<saml:SubjectConfirmationData />
</saml:SubjectConfirmation>
```

If I understand correctly the spec it should probably be 

```
<saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
	<saml:SubjectConfirmationData Recipient="copyValueOfCallbackUrl" NotOnOrAfter="currentTime+sessionDuration" InResponseTo="theRequestIdThatWasSent"/>
</saml:SubjectConfirmation>
```
(By the way I tried to test a cxf-fediz setup, and it complains about these missing properties)

**Comment by fujifish** [comment]
Fixed
